spring.application.name=sttalisconnect
spring.datasource.url=jdbc:postgresql://localhost:5432/sttalisconnect
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

#Fase Debug DDL-Auto
#Em Producao Flayway
spring.jpa.hibernate.ddl-auto=update
#imprime o SQL gerado no console modo-debug
spring.jpa.show-sql=true

app.allowed-origins=${ALLOWED_ORIGINS}