spring.datasource.url=${DB_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

#Fase Debug DDL-Auto
#Em Producao Flayway
spring.jpa.hibernate.ddl-auto=update
#imprime o SQL gerado no console modo-debug
spring.jpa.show-sql=false

app.allowed-origins=${ALLOWED_ORIGINS}
api.security.token.secret=${JWT_SECRET}